/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterIndexRouteImport } from './routes/register/index'
import { Route as LoginIndexRouteImport } from './routes/login/index'
import { Route as CheckoutIndexRouteImport } from './routes/checkout/index'
import { Route as AboutIndexRouteImport } from './routes/about/index'
import { Route as homeIndexRouteImport } from './routes/(home)/index'
import { Route as ProductProductIDRouteImport } from './routes/product/$productID'

const RegisterIndexRoute = RegisterIndexRouteImport.update({
  id: '/register/',
  path: '/register/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutIndexRoute = CheckoutIndexRouteImport.update({
  id: '/checkout/',
  path: '/checkout/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutIndexRoute = AboutIndexRouteImport.update({
  id: '/about/',
  path: '/about/',
  getParentRoute: () => rootRouteImport,
} as any)
const homeIndexRoute = homeIndexRouteImport.update({
  id: '/(home)/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductProductIDRoute = ProductProductIDRouteImport.update({
  id: '/product/$productID',
  path: '/product/$productID',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/product/$productID': typeof ProductProductIDRoute
  '/': typeof homeIndexRoute
  '/about': typeof AboutIndexRoute
  '/checkout': typeof CheckoutIndexRoute
  '/login': typeof LoginIndexRoute
  '/register': typeof RegisterIndexRoute
}
export interface FileRoutesByTo {
  '/product/$productID': typeof ProductProductIDRoute
  '/': typeof homeIndexRoute
  '/about': typeof AboutIndexRoute
  '/checkout': typeof CheckoutIndexRoute
  '/login': typeof LoginIndexRoute
  '/register': typeof RegisterIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/product/$productID': typeof ProductProductIDRoute
  '/(home)/': typeof homeIndexRoute
  '/about/': typeof AboutIndexRoute
  '/checkout/': typeof CheckoutIndexRoute
  '/login/': typeof LoginIndexRoute
  '/register/': typeof RegisterIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/product/$productID'
    | '/'
    | '/about'
    | '/checkout'
    | '/login'
    | '/register'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/product/$productID'
    | '/'
    | '/about'
    | '/checkout'
    | '/login'
    | '/register'
  id:
    | '__root__'
    | '/product/$productID'
    | '/(home)/'
    | '/about/'
    | '/checkout/'
    | '/login/'
    | '/register/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ProductProductIDRoute: typeof ProductProductIDRoute
  homeIndexRoute: typeof homeIndexRoute
  AboutIndexRoute: typeof AboutIndexRoute
  CheckoutIndexRoute: typeof CheckoutIndexRoute
  LoginIndexRoute: typeof LoginIndexRoute
  RegisterIndexRoute: typeof RegisterIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register/': {
      id: '/register/'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/': {
      id: '/checkout/'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about/': {
      id: '/about/'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(home)/': {
      id: '/(home)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof homeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$productID': {
      id: '/product/$productID'
      path: '/product/$productID'
      fullPath: '/product/$productID'
      preLoaderRoute: typeof ProductProductIDRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  ProductProductIDRoute: ProductProductIDRoute,
  homeIndexRoute: homeIndexRoute,
  AboutIndexRoute: AboutIndexRoute,
  CheckoutIndexRoute: CheckoutIndexRoute,
  LoginIndexRoute: LoginIndexRoute,
  RegisterIndexRoute: RegisterIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
